services:
  backend:
    build: ../../../backend/src/studyweb/systems/web22_tanstack_query/backend
    ports:
      - "13022:3000"
  frontend:
    build: ../../../frontend/src/studyweb/systems/web22_tanstack_query/frontend
    environment:
      VITE_API_URL: http://localhost:13022
    ports:
      - "5182:5173"
    depends_on:
      - backend

